### ISSUE TITLE
Error al instalar psycopg2 via poetry

### ISSUE THREAD

**Issue by kanroot** [corp-0/artemanga#1]
Al momento de intentar instalar psycopg2 se produce el siguiente error:

    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [23 lines of output]
        running egg_info
        creating /tmp/pip-pip-egg-info-tne_4ja0/psycopg2.egg-info
        writing /tmp/pip-pip-egg-info-tne_4ja0/psycopg2.egg-info/PKG-INFO
        writing dependency_links to /tmp/pip-pip-egg-info-tne_4ja0/psycopg2.egg-info/dependency_links.txt
        writing top-level names to /tmp/pip-pip-egg-info-tne_4ja0/psycopg2.egg-info/top_level.txt
        writing manifest file '/tmp/pip-pip-egg-info-tne_4ja0/psycopg2.egg-info/SOURCES.txt'
        
        Error: pg_config executable not found.
        
        pg_config is required to build psycopg2 from source.  Please add the directory
        containing pg_config to the $PATH or specify the full executable path with the
        option:
        
            python setup.py build_ext --pg-config /path/to/pg_config build ...
        
        or with the pg_config option in 'setup.cfg'.
        
        If you prefer to avoid building psycopg2 from source, please install the PyPI
        'psycopg2-binary' package instead.
        
        For further information please check the 'doc/src/install.rst' file (also at
        <https://www.psycopg.org/docs/install.html>).
        
        [end of output]

Se soluciona añadiendo como un paquete requerido a instalar _postgresql_

**Comment by corp-0** [comment]
posible solución: quitar psycopg2 de los requisitos y poner psycopg2-binaries

**Comment by corp-0** [comment]
debería estar solucionado con #66
