### ISSUE TITLE
Reverse for '/confirmar-compra/' not found. '/confirmar-compra/' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by kanroot** [corp-0/artemanga#147]
Al momento de confirmar una compra y no se tiene direccion, se le solicita crear una, al crearla aparece el siguiente error `NoReverseMatch at /crear-direccion/

Reverse for '/confirmar-compra/' not found. '/confirmar-compra/' is not a valid view function or pattern name.`

**Comment by corp-0** [comment]
te animas a resolver ese bug?

**Comment by kanroot** [comment]
subi un pull que lo soluciona, dale una mirada.
