### ISSUE TITLE
Crear modelos de Django a partir del MER

### ISSUE THREAD

**Issue by corp-0** [corp-0/artemanga#33]
Historias relacionadas: 
- #14 
- #15 
- #16

**Comment by kanroot** [comment]
- [ ] Corregir la tabla Usuario
- [ ] Crear tablas
- [ ] Añadir conexiones
- [ ] Realizar migraciones

**Comment by kanroot** [comment]
- [ ] Crear los modulos respectivos
- [ ] Seperar la logica del modulo catalogo a los respectivos

**Comment by kanroot** [comment]
- [ ] Elimación de propiedades repetidas
