### ISSUE TITLE
Crear página CRUD para gestionar inventario

### ISSUE THREAD

**Issue by corp-0** [corp-0/artemanga#34]
Depende de:
- #33 

Historias relacionadas:
- #14 
- #15 
- #16

**Comment by kanroot** [comment]
- [ ] Crear ``urls.py`` en el directorio del módulo e incluir las definiciones en el ``urls.py`` del proyecto.
- [ ] Crear directorio ``templates`` en el módulo y construír html básico.
- [ ] Crear ``forms.py`` en el directorio del módulo y definir los campos que conformarán la vista específica.
- [ ] Crear ``views.py`` en el directorio del módulo y definir el comportamiento de la vista.
